#!/bin/bash
# Bootstrap script for ADP1Research Python virtual environment setup
# Generated by Claude Code

set -e  # Exit on error

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
KBUTILLIB_PATH="/home/chenry/projects/ClaudeProjects/KBUtilLib"

echo "🔧 Setting up Python virtual environment for ADP1Research..."
echo "📍 Project directory: $PROJECT_DIR"
echo ""

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo "❌ Error: python3 is not installed"
    exit 1
fi

PYTHON_VERSION=$(python3 --version)
echo "🐍 Using: $PYTHON_VERSION"
echo ""

# Create virtual environment if it doesn't exist
if [ ! -d "$VENV_DIR" ]; then
    echo "📦 Creating virtual environment at $VENV_DIR..."
    python3 -m venv "$VENV_DIR"
    echo "✅ Virtual environment created"
else
    echo "✅ Virtual environment already exists at $VENV_DIR"
fi
echo ""

# Activate virtual environment
echo "🔌 Activating virtual environment..."
source "$VENV_DIR/bin/activate"
echo "✅ Activated: $(which python)"
echo ""

# Upgrade pip
echo "⬆️  Upgrading pip..."
pip install --upgrade pip setuptools wheel
echo ""

# Install dependencies
if [ -f "$PROJECT_DIR/requirements.txt" ]; then
    echo "📚 Installing dependencies from requirements.txt..."
    pip install -r "$PROJECT_DIR/requirements.txt"
    echo "✅ Core dependencies installed"
    echo ""
else
    echo "⚠️  No requirements.txt found"
    echo ""
fi

# Install KBUtilLib in editable mode if available
if [ -d "$KBUTILLIB_PATH" ]; then
    echo "📦 Installing KBUtilLib from $KBUTILLIB_PATH (editable mode)..."

    # Check if KBUtilLib has dependencies
    if [ -f "$KBUTILLIB_PATH/requirements.txt" ]; then
        echo "   Installing KBUtilLib dependencies..."
        pip install -r "$KBUTILLIB_PATH/requirements.txt"
    fi

    # Install KBUtilLib in editable mode
    if [ -f "$KBUTILLIB_PATH/setup.py" ] || [ -f "$KBUTILLIB_PATH/pyproject.toml" ]; then
        pip install -e "$KBUTILLIB_PATH"
    else
        echo "   ⚠️  KBUtilLib found but has no setup.py or pyproject.toml"
        echo "   ⚠️  You may need to configure PYTHONPATH manually"
    fi

    echo "✅ KBUtilLib configured"
    echo ""
else
    echo "⚠️  KBUtilLib not found at $KBUTILLIB_PATH"
    echo "   The project may not work correctly without it"
    echo "   Expected location: $KBUTILLIB_PATH"
    echo ""
fi

# Install ADP1Notebooks if it has a setup file
ADP1_NOTEBOOKS="$PROJECT_DIR/ADP1Notebooks"
if [ -d "$ADP1_NOTEBOOKS" ]; then
    if [ -f "$ADP1_NOTEBOOKS/setup.py" ] || [ -f "$ADP1_NOTEBOOKS/pyproject.toml" ]; then
        echo "📦 Installing ADP1Notebooks (editable mode)..."
        pip install -e "$ADP1_NOTEBOOKS"
        echo "✅ ADP1Notebooks installed"
        echo ""
    fi
fi

echo ""
echo "🎉 Setup complete!"
echo ""
echo "📊 Installed packages:"
pip list | grep -E "(pandas|numpy|cobra|jupyter|escher|openpyxl)" || echo "  (Core packages listed above)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ To activate the virtual environment, run:"
echo "   source .venv/bin/activate"
echo ""
echo "Or use the helper script:"
echo "   source ./activate_venv.sh"
echo ""
echo "To deactivate when you're done, run:"
echo "   deactivate"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
